
version: '3'
services:

  #PHP Service
  graphr_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: graphr_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./../Scrapr/images:/var/www/public/img/fonts
      - ./../Scrapr/files:/var/www/public/files/fonts
      - ./../Scrapr/meta:/var/www/public/files/meta
    networks:
      - app-network

  #Nginx Service
  graphr_nginx:
    image: nginx:1.17.8-alpine
    container_name: graphr_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./../Scrapr/images:/var/www/public/img/fonts
      - ./../Scrapr/files:/var/www/public/files/fonts
      - ./../Scrapr/meta:/var/www/public/files/meta
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
